#!/usr/bin/env python
# /home/scrapbook/tutorial/.git/hooks/Devops_Training/post-commit

git push origin master

PWD = '/home/scrapbook/tutorial/.git/hooks/Devops_Training/post-commit'

git config --global user.name = "Jahnavi4623"

signingKey = git config --global --get user.signingkey

git config --global user.email = "janu6264@gmail.com"

import webbrowser

webbrowser.open("https://github.com")
